#!/bin/sh

# Function to set wallpaper and store the path
set_wallpaper() {
    feh --bg-scale "$1"
    echo "$1" > ~/.config/i3/Scripts/feh_last_wallpaper.sh
}

while read file
do
        case "$1" in
        #"C-d")
        #       mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
		"C-f")
				set_wallpaper "$file" ;;
        "C-d")
                file "$file" ;;
        esac
done
