;;; grep-a-lot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from grep-a-lot.el

(autoload 'grep-a-lot-advise "grep-a-lot" "\
Advise a grep-like function FUNC with an around-type advice,
so as to enable multiple search results buffers.

(fn FUNC)" nil t)
(autoload 'grep-a-lot-setup-keys "grep-a-lot" "\
Define some key bindings for navigating multiple
grep search results buffers." t)
(register-definition-prefixes "grep-a-lot" '("grep-a-lot-"))

;;; End of scraped data

(provide 'grep-a-lot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; grep-a-lot-autoloads.el ends here
