general.import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[font]
size = 10

[font.bold]
#family = "Jetbrains Mono"
family = "PrasevkaIomataMNLv2 Nerd Font"
#family = "Lilex"
# family = "Terminus Nerd Font"
# family = "Terminus"
style = "Bold"

[font.bold_italic]
#family = "Jetbrains Mono"
family = "PrasevkaIomataMNLv2 Nerd Font"
#family = "Lilex"
#family = "Terminus"
style = "Bold Italic"

[font.italic]
#family = "Jetbrains Mono"
family = "PrasevkaIomataMNLv2 Nerd Font"
#family = "Lilex"
#family = "Terminus"
style = "Italic"

[font.normal]
#family = "Jetbrains Mono"
family = "PrasevkaIomataMNLv2 Nerd Font"
#family = "Lilex"
#family = "Terminus"
style = "Regular"


[window]
opacity = 1
blur = true

